<?php

namespace DemandeBundle\Repository;

/**
 * CategorieDemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDemRepository extends \Doctrine\ORM\EntityRepository
{
}
