evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }
evenement_liste:
    path:     /liste
    defaults: { _controller: EvenementBundle:Default:liste }
evenement_com:
    path:     /addcom
    defaults: { _controller: EvenementBundle:Default:addcom }
evenement_suppr_com:
    path:     /supprimercom/{idcom}
    defaults: { _controller: EvenementBundle:Default:supprimercom }
evenement_participer:
    path:     /participer{id}
    defaults: { _controller: EvenementBundle:Default:participer }
evenement_annuler:
    path:     /annuler/{id}
    defaults: { _controller: EvenementBundle:Default:annuler }

evenement_edit:
    path:     /{id}/modifier
    defaults: { _controller: EvenementBundle:Default:edit }

evenement_delete:
    path:     /{id}/supprimer
    defaults: { _controller: EvenementBundle:Default:delete }