<?php

namespace AppBundle\Repository;

/**
 * AdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdresseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGouvernorat()
    {
        return $this->getEntityManager()->createQuery(
        "select a from AppBundle:Adresse a where a.IdParent IS NULL"
        )
        ->getArrayResult();
    }

    public function getDelegation($gouvernorat)
    {
        return $this->getEntityManager()->createQuery(
            "select a from AppBundle:Adresse a where a.IdParent =".$gouvernorat
        )
            ->getArrayResult();
    }
}
