demande:
    resource: "@DemandeBundle/Resources/config/routing.yml"
    prefix:   /demande

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /produit

service:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /service

app:
    resource: '@AppBundle/Controller/'
    type: annotation
