demande_homepage:
    path:     /
    defaults: { _controller: DemandeBundle:Default:index }

demande:
    path:     /dem
    defaults: { _controller: DemandeBundle:Default:demande }

demande:
    path:     /lstdem
    defaults: { _controller: DemandeBundle:Default:lstdemande }
