<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercheAll($categorie,$date,$adresse){
        $req = $this->getEntityManager()->createQuery("select v from EvenementBundle:Evenement v 
              WHERE v.categorie='$categorie' OR v.startTime='$date' OR v.adresse>='$adresse'")
            ->getResult();
        return $req;
    }
    public function count($id){
        $query=$this->getEntityManager()
            ->createQuery("update EvenementBundle:Evenement e set e.nbrParticipants=e.nbrParticipants+1 where e.id='$id'");
        $query->getResult();
        $query2=$this->getEntityManager()
            ->createQuery("select e from EvenementBundle:Evenement e where e.id='$id'");
        return $query2->getResult();
    }
}
