<?php

namespace ServiceBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function FiltreService($titre,$categorie,$gouvernorat,$delegation,$etat)
    {
        $req1="";
        $req2="";
        $req3="";
        $req4="";
        $req5="";

        if (strcmp($titre,"")!=0)
            $req1=" and s.TitreService = '".$titre."'";
        if ($categorie!=-1)
            $req2=" and d.id =".$categorie;
        if ($gouvernorat!=-1)
            $req3=" and a1.idAdresse =".$gouvernorat;
        if ($delegation!=-1)
            $req4=" and a2.idAdresse =".$delegation;
        if ($etat!=-1)
            $req5=" and s.EtatService = ".$etat;

        $req6 = "select s.TitreService,s.DescriptionService,d.nom CategorieService,s.PrixService,s.DateCreationService
                    ,s.EtatService,s.NoteService, a1.Libelle GouvernoratService, a2.Libelle  DelegationService
                    from ServiceBundle:Service s, AppBundle:Categorie d, AppBundle:Adresse a1, AppBundle:Adresse a2
                    where d.id=s.CategorieService and a1.idAdresse = s.GouvernoratService and a2.idAdresse=s.DelegationService"
                    .$req1." ".$req2." ".$req3." ".$req4." ".$req5;

        return $this->getEntityManager()->createQuery($req6)->getArrayResult();
    }

    public function FiltreServiceAll()
    {
        return $this->getEntityManager()->createQuery(
            "select s.TitreService,s.DescriptionService,d.nom CategorieService,s.PrixService,s.DateCreationService
                    ,s.EtatService,s.NoteService, a1.Libelle GouvernoratService, a2.Libelle  DelegationService
                    from ServiceBundle:Service s, AppBundle:Categorie d, AppBundle:Adresse a1, AppBundle:Adresse a2
                    where d.id=s.CategorieService and a1.idAdresse = s.GouvernoratService and a2.idAdresse=s.DelegationService"
        )
            ->getArrayResult();
    }
}
