<?php

namespace ProduitBundle\Repository;

/**
 * CategorieProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProRepository extends \Doctrine\ORM\EntityRepository
{
}
