<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZirxipw\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZirxipw/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZirxipw.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZirxipw\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZirxipw\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zirxipw',
    'container.build_id' => '78fbc47a',
    'container.build_time' => 1562262989,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZirxipw');
