<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBifrzxz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBifrzxz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBifrzxz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBifrzxz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerBifrzxz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Bifrzxz',
    'container.build_id' => 'a8e7f272',
    'container.build_time' => 1562886091,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBifrzxz');
