<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRojsm0h\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRojsm0h/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRojsm0h.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRojsm0h\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRojsm0h\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Rojsm0h',
    'container.build_id' => '0137377d',
    'container.build_time' => 1562884103,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRojsm0h');
